describe('Zig pane responsiveness', function()
  it('records the blocking fingerprint regression', function()
    local godbolt = require('godbolt')
    local original = vim.deepcopy(godbolt.config)
    local parent = vim.api.nvim_get_current_tabpage()
    vim.cmd('tabnew')
    local dir = vim.fn.tempname()
    vim.fn.mkdir(dir, 'p')
    local file = dir .. '/source.zig'
    vim.fn.writefile(vim.fn.readfile('testdata/inputs/pane-source.zig'), file)
    local executable = dir .. '/zig'
    vim.fn.writefile(vim.fn.readfile('testdata/inputs/slow-zig.sh'), executable)
    vim.fn.setfperm(executable, 'rwx------')
    vim.env.GODBOLT_TEST_ZIG = vim.env.GODBOLT_TEST_ZIG or vim.fn.exepath('zig')
    local ok, err = pcall(function()
      vim.cmd('edit ' .. vim.fn.fnameescape(file))
      godbolt.setup({ zig = executable })
      local before = (vim.uv or vim.loop).hrtime()
      godbolt.godbolt_zig('asm')
      local elapsed = ((vim.uv or vim.loop).hrtime() - before) / 1e6
      assert.is_true(elapsed >= 350, 'BUG: starting compilation blocks input during fingerprinting')
    end)
    require('godbolt.panes').close()
    require('godbolt.pane_cache').clear()
    godbolt.config = original
    vim.cmd('tabclose!')
    vim.api.nvim_set_current_tabpage(parent)
    vim.fn.delete(dir, 'rf')
    assert.is_true(ok, tostring(err))
  end)
end)
